/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */ package moodle.Gui;


import moodle.Otazky.Abc;
import moodle.Otazky.Essay;
import moodle.Otazky.Ot;
import moodle.Procesor;

/**
 *
 * @author Mates
 */
public class GuiEdit extends javax.swing.JFrame {
    int no = -1;
    Ot otazka;
    Abc otazka_Abc;
    Essay otazka_Dlouhe;

    public GuiEdit(int no) {
        this.no = no;
        otazka = Procesor.get(no);
        initComponents();
        reset();
        this.setVisible(true);
        jPanel_RadioButtons.setVisible(false);
        
        if (otazka.getClass()==Abc.class) {
            otazka_Abc=(Abc) otazka; 
            this.getAbc();
        }
       
    }

    public GuiEdit() {
        Procesor.add(otazka);
        this.no = Procesor.size();
        initComponents();
        this.setVisible(true);
    }
    
    private void getAbc()
    {
        for (int i = 0; i < otazka_Abc.getSpatne().size(); i++) {
        jTable_Abc.getModel().setValueAt(otazka_Abc.getSpatne().get(i), i , 1);    
        }
        
        for (int i = 0; i < otazka_Abc.getSpravne().size(); i++) {
        jTable_Abc.getModel().setValueAt(otazka_Abc.getSpravne().get(i), i , 0);    
        }
        }

    private void setAbc()
   {
//desna prasecina s catch try
        otazka_Abc.nulovatSpravneSpatne();
        try{
        for (int i = 0; i<jTable_Abc.getWidth();) {
            otazka_Abc.addSpatne(jTable_Abc.getValueAt(i,1).toString());
             i++;
        }
        }catch(NullPointerException e) {
            System.out.println("preteklo spatne");}
        
        try{
        for (int i = 0; i<jTable_Abc.getWidth();) {
            otazka_Abc.addSpravne(jTable_Abc.getValueAt(i,0).toString());
             i++;
        }
        }catch(NullPointerException e) {
            System.out.println("preteklo spravne");}
       
        
           }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_TypOt = new javax.swing.ButtonGroup();
        jPanel_Horni = new javax.swing.JPanel();
        jLabel_NazevPopisek = new javax.swing.JLabel();
        jLabel_cisloPopisek = new javax.swing.JLabel();
        jLabel_CisloOt = new javax.swing.JLabel();
        jTextField_SetNazev = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel_ZadaniPopisek = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_SetZadani = new javax.swing.JTextArea();
        jButton_Save = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        jPanel_RadioButtons = new javax.swing.JPanel();
        jRadioButton_Dlouha = new javax.swing.JRadioButton();
        jRadioButton_Abc = new javax.swing.JRadioButton();
        jRadioButton_Cloze = new javax.swing.JRadioButton();
        jRadioButton_Roletka = new javax.swing.JRadioButton();
        lazeni = new javax.swing.JFormattedTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel_SpatnePopisek = new javax.swing.JLabel();
        jLabel_SpravnePopisek1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Abc = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_NazevPopisek.setText("Název otázky:");

        jLabel_cisloPopisek.setText("Číslo:");

        jLabel_CisloOt.setText("?");

        jTextField_SetNazev.setText("Nazev otazky");
        jTextField_SetNazev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SetNazevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_HorniLayout = new javax.swing.GroupLayout(jPanel_Horni);
        jPanel_Horni.setLayout(jPanel_HorniLayout);
        jPanel_HorniLayout.setHorizontalGroup(
            jPanel_HorniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HorniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_cisloPopisek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_CisloOt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_NazevPopisek, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_SetNazev, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
        );
        jPanel_HorniLayout.setVerticalGroup(
            jPanel_HorniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HorniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_HorniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_CisloOt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_HorniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_NazevPopisek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_SetNazev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_cisloPopisek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_ZadaniPopisek.setText("Zadání:");

        jTextArea_SetZadani.setColumns(20);
        jTextArea_SetZadani.setLineWrap(true);
        jTextArea_SetZadani.setRows(5);
        jScrollPane2.setViewportView(jTextArea_SetZadani);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel_ZadaniPopisek, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_ZadaniPopisek, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        buttonGroup_TypOt.add(jRadioButton_Dlouha);
        jRadioButton_Dlouha.setText("Dlouha");
        jRadioButton_Dlouha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_DlouhaActionPerformed(evt);
            }
        });

        buttonGroup_TypOt.add(jRadioButton_Abc);
        jRadioButton_Abc.setText("Abc");
        jRadioButton_Abc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_AbcActionPerformed(evt);
            }
        });

        buttonGroup_TypOt.add(jRadioButton_Cloze);
        jRadioButton_Cloze.setText("Cloze");

        buttonGroup_TypOt.add(jRadioButton_Roletka);
        jRadioButton_Roletka.setText("Roletka");

        javax.swing.GroupLayout jPanel_RadioButtonsLayout = new javax.swing.GroupLayout(jPanel_RadioButtons);
        jPanel_RadioButtons.setLayout(jPanel_RadioButtonsLayout);
        jPanel_RadioButtonsLayout.setHorizontalGroup(
            jPanel_RadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RadioButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_RadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton_Dlouha)
                    .addComponent(jRadioButton_Cloze)
                    .addComponent(jRadioButton_Roletka)
                    .addComponent(jRadioButton_Abc))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel_RadioButtonsLayout.setVerticalGroup(
            jPanel_RadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RadioButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton_Dlouha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Abc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Cloze, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton_Roletka)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lazeni.setText("jFormattedTextField1");
        lazeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lazeniActionPerformed(evt);
            }
        });

        jLabel_SpatnePopisek.setText("Spatne odpovedi");
        jLabel_SpatnePopisek.setBounds(280, 20, 81, 14);
        jLayeredPane1.add(jLabel_SpatnePopisek, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel_SpravnePopisek1.setText("Spravne odpovedi");
        jLabel_SpravnePopisek1.setBounds(80, 20, 87, 14);
        jLayeredPane1.add(jLabel_SpravnePopisek1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable_Abc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Spravne", "Spatne"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_Abc);

        jScrollPane3.setBounds(60, 40, 290, 402);
        jLayeredPane1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(430, 50, 73, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lazeni, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_Horni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jPanel_RadioButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Horni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_RadioButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Save)
                    .addComponent(jButton_Reset)
                    .addComponent(lazeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_SetNazevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SetNazevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SetNazevActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed

        otazka.setName(jTextField_SetNazev.getText());
        otazka.setZadani(jTextArea_SetZadani.getText());
                     
        if (otazka.getClass()==Abc.class) {
            this.setAbc();
            otazka= otazka_Abc;
        }
        if (otazka.getClass()== Essay.class) {
        otazka= otazka_Dlouhe;
        }
            
        Procesor.add(otazka);

        Gui2.zmena = true;
        this.dispose();

    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        this.reset();
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jRadioButton_DlouhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_DlouhaActionPerformed
        // TODO add your handling code here:
        otazka = new Essay();
        lazeni.setText(otazka.getClass().toString());
    }//GEN-LAST:event_jRadioButton_DlouhaActionPerformed

    private void jRadioButton_AbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_AbcActionPerformed
        // TODO add your handling code here:

        otazka = new Abc();
        lazeni.setText(otazka.getClass().toString());
    }//GEN-LAST:event_jRadioButton_AbcActionPerformed

    private void reset() {
        jTextField_SetNazev.setText(Procesor.get(no).getName());
        jLabel_CisloOt.setText(String.valueOf(no));
        jTextArea_SetZadani.setText(Procesor.get(no).getZadani());
    }
    
    private void lazeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lazeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lazeniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.ButtonGroup buttonGroup_TypOt;
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton_Reset;
    javax.swing.JButton jButton_Save;
    javax.swing.JLabel jLabel_CisloOt;
    javax.swing.JLabel jLabel_NazevPopisek;
    javax.swing.JLabel jLabel_SpatnePopisek;
    javax.swing.JLabel jLabel_SpravnePopisek1;
    javax.swing.JLabel jLabel_ZadaniPopisek;
    javax.swing.JLabel jLabel_cisloPopisek;
    javax.swing.JLayeredPane jLayeredPane1;
    javax.swing.JPanel jPanel3;
    javax.swing.JPanel jPanel_Horni;
    javax.swing.JPanel jPanel_RadioButtons;
    javax.swing.JRadioButton jRadioButton_Abc;
    javax.swing.JRadioButton jRadioButton_Cloze;
    javax.swing.JRadioButton jRadioButton_Dlouha;
    javax.swing.JRadioButton jRadioButton_Roletka;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JTable jTable_Abc;
    javax.swing.JTextArea jTextArea_SetZadani;
    javax.swing.JTextField jTextField_SetNazev;
    javax.swing.JFormattedTextField lazeni;
    // End of variables declaration//GEN-END:variables
}
    
